### ISSUE TITLE
Wrong name package.js 

### ISSUE THREAD

**Issue by smeedijzer-internet** [markusantonwolf/ta-youtube#2]
Hi,

Shouldn't the package name be something like: ta-youtube?

https://github.com/markusantonwolf/ta-youtube/blob/98ac862def941c5fd17c7d516c9e0cdfc7a2cb3e/package.json#L2

And, can I install this package with npm?

**Comment by RJFares** [comment]
Also +1 on the npm packaging, you made amazing libs and it would be great if we can integrate them with one command in any project, and let our build process minify the css without worrying which css folder to include ;)

**Comment by markusantonwolf** [comment]
Thank you - I fixed it with the new version 2.X and now it is available at NPM as a Tailwind CSS Plugin: https://www.npmjs.com/package/@markusantonwolf/ta-youtube
